# Generated by Django 5.2.6 on 2025-11-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='article',
        ),
    ]
